### ISSUE TITLE
Support for "local" loggers

### ISSUE THREAD

**Issue by phtrivier** [AirVantage/node-tech-logger#5]
I think it would be nice to be able to do something like : 

```
// in file like techFoo.js of node-tech-foo

var logger  = require("node-tech-logger").prefixed("tech-foo");

... 

logger.debug("Some message");
```

And the "local" function would return a wrapped logger that would simply prefix all messages so that you get :

```
debug : [tech-foo] Some message
```

(Or maybe even file info if it make sense : 

```
var logger  = require("node-tech-logger").prefixed("tech-foo", __dirname);
```

```
debug : [tech-foo] [techFoo.js] Some message
```

Is that something that winston / whatever supports out of the box ?

**Comment by sebz** [comment]
Fixed with https://github.com/AirVantage/node-tech-logger/pull/6
